#!/bin/sh

model=`cat /proc/device-tree/model`

# Pi 3A+ is also ttyAMA0
if [ "${model:0:20}" = "Raspberry Pi 3 ModelXX" -o "${model:0:19}" = "Raspberry Pi Zero W" ]; then
    port=ttyS0
else
    port=ttyAMA0
fi

# ttyGS0 is USB-gadget serial

# Start serial terminal on Raspberry Pi
while :
do
  port=/dev/ttyGS0
  echo Start serial on $port
  /sbin/getty -L $port 115200 screen
  sleep 3
done
